title: Sep's Portfolio
email: sepvenmuel@gmail.com
description: >-
  Welcome to my corner of the internet — a showcase of my journey as an Electrical and Computer Engineering graduate, where I document my proudest accomplishments, personal projects, and the skills I've built along the way, all driven by a passion for innovation, technology, and continuous self-improvement.
twitter_username: username
github_username: sepcabanizas
minimal_mistakes_skin: default
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: 
include:
  - _pages
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
author:
  name   : "Sep Venmuel F. Cabanizas"
  avatar : "/assets/bio-photo.jpg"
  bio    : "I hold a B.S. in Electrical and Computer Engineering, and when I'm not engineering the future, you can find me building cool projects in the lab, dominating in video games, hitting PRs at the gym, and turning heads with my love for cars.
"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/sepvfc/"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/sepvfc/"
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_excerpts: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
